import Footer from "@/_componentsToUse/footer";
import Header from "@/_componentsToUse/header";
import './global.css'


export const metadata = {
  title: "!Best App ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
