import './global.css'
import AppShell from "./AppShell";


export const metadata = {
  title: "!Best App ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppShell>
          {children}
        </AppShell>
      </body>
    </html>
  );
}
